use_frameworks!

target 'ViewHighlighter_Example' do
  pod 'ViewHighlighter', :path => '../'

  target 'ViewHighlighter_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
